copy release\scripts\startup\bl_ui\properties_data_modifier.py J:\Blender---AMA\release\scripts\startup\bl_ui /Y
copy source\blender\blenkernel\BKE_ama.h J:\Blender---AMA\source\blender\blenkernel /Y
copy source\blender\blenkernel\CMakeLists.txt J:\Blender---AMA\source\blender\blenkernel /Y
copy source\blender\blenkernel\intern\ama.c J:\Blender---AMA\source\blender\blenkernel\intern /Y
copy source\blender\blenkernel\intern\anim.c J:\Blender---AMA\source\blender\blenkernel\intern /Y
copy source\blender\blenloader\intern\readfile.c J:\Blender---AMA\source\blender\blenloader\intern /Y
copy source\blender\blenloader\intern\writefile.c J:\Blender---AMA\source\blender\blenloader\intern /Y
copy source\blender\editors\object\object_intern.h J:\Blender---AMA\source\blender\editors\object /Y
copy source\blender\editors\object\object_modifier.c J:\Blender---AMA\source\blender\editors\object /Y
copy source\blender\editors\object\object_ops.c J:\Blender---AMA\source\blender\editors\object /Y
copy source\blender\makesdna\DNA_modifier_types.h J:\Blender---AMA\source\blender\makesdna /Y
copy source\blender\makesdna\DNA_object_types.h J:\Blender---AMA\source\blender\makesdna /Y
copy source\blender\makesdna\DNA_group_types.h J:\Blender---AMA\source\blender\makesdna /Y
copy source\blender\makesrna\intern\rna_modifier.c J:\Blender---AMA\source\blender\makesrna\intern /Y
copy source\blender\modifiers\intern\MOD_array.c J:\Blender---AMA\source\blender\modifiers\intern /Y
copy source\blender\render\intern\source\convertblender.c J:\Blender---AMA\source\blender\render\intern\source /Y
copy patch-ama J:\Blender---AMA\patch-ama /Y